# Generated by Django 5.2.1 on 2025-05-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255)),
                ('cust_age', models.IntegerField()),
                ('cust_city', models.CharField(max_length=255)),
                ('cust_order_details', models.CharField(max_length=255)),
            ],
        ),
    ]
